### ISSUE TITLE
MDMC

### ISSUE THREAD

**Issue by systemdlul** [WitherOrNot/MuseDashDLCUnlock#1]
First of all: Thank you for creating this mod!

Now, the issue: Is there a way to make this mod work with MDMC? Again, Thanks. 

`mdmc.moe`

**Comment by WitherOrNot** [comment]
MDMC seems to use MelonLoader, so it should work just fine, are there any specific issues?

**Comment by systemdlul** [comment]
It seems they're using a modified version of the MelonLoader installer, here's a screenshot: https://i.imgur.com/5N13SV9.png

Edit: Same error occurs during a fresh install with only your file in the 'mods" folder.

**Comment by WitherOrNot** [comment]
I think you are missing an installation of .NET 6.0: https://dotnet.microsoft.com/en-us/download/dotnet/6.0

Please install this then try again.

**Comment by systemdlul** [comment]
I reinstalled .NET and got the same error using their version of melonloader. Regular version works fine.

'latest.log' output: https://pastebin.com/SAt2F4vZ

**Comment by WitherOrNot** [comment]
Hello, I have fixed this issue, it was caused by .NET version incompatibility, as MDMC uses .NET Framework 4.8. I will add a MDMC-supporting DLL to the Releases section.

![image](https://github.com/WitherOrNot/MuseDashDLCUnlock/assets/26913821/f38aafab-7cc7-4afd-bf5e-173f0a87f164)

![image](https://github.com/WitherOrNot/MuseDashDLCUnlock/assets/26913821/9031243e-3894-4048-a833-df12d76e4029)
